/** Generated by scripts/refresh-catalog-pricing.ts — do not edit by hand. */
export const BUILD_CATALOG_PRICING = {
  "source": "snapshot-fallback",
  "tours": [
    {
      "id": "snap-city",
      "slug": "city",
      "price_per_person_cents": 40000,
      "max_guests": 5
    },
    {
      "id": "snap-peninsula",
      "slug": "peninsula",
      "price_per_person_cents": 90000,
      "max_guests": 5
    },
    {
      "id": "snap-winelands",
      "slug": "winelands",
      "price_per_person_cents": 80000,
      "max_guests": 5
    },
    {
      "id": "snap-sunset",
      "slug": "sunset",
      "price_per_person_cents": 50000,
      "max_guests": 5
    },
    {
      "id": "snap-hermanus",
      "slug": "hermanus",
      "price_per_person_cents": 340000,
      "max_guests": 5
    }
  ],
  "vehicles": [
    {
      "id": "snap-corolla",
      "slug": "corolla",
      "name": "Toyota Corolla Cross GR Sport",
      "capacity_min": 1,
      "capacity_max": 3,
      "vehicle_price_cents": 250000,
      "is_luxury": false
    },
    {
      "id": "snap-suzuki",
      "slug": "suzuki",
      "name": "Suzuki XL6",
      "capacity_min": 1,
      "capacity_max": 5,
      "vehicle_price_cents": 320000,
      "is_luxury": false
    },
    {
      "id": "snap-mercedes",
      "slug": "mercedes",
      "name": "Mercedes-Benz GLC 220 Coupe",
      "capacity_min": 1,
      "capacity_max": 3,
      "vehicle_price_cents": 450000,
      "is_luxury": true
    }
  ]
} as const
