/**
 * Build step: load tour + vehicle prices from Supabase (read-only anon) for prerender / From labels.
 * Falls back to CATALOG_PRICING_SNAPSHOT_FALLBACK when fetch fails.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createClient } from '@supabase/supabase-js'
import { CATALOG_PRICING_SNAPSHOT_FALLBACK } from '../client/src/data/catalogPricing.snapshot.ts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, '..', 'client', 'src', 'data', 'catalogPricing.generated.ts')

function loadEnvFile(filePath: string) {
  if (!fs.existsSync(filePath)) return
  const text = fs.readFileSync(filePath, 'utf8')
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq < 0) continue
    const key = trimmed.slice(0, eq).trim()
    let val = trimmed.slice(eq + 1).trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    if (!process.env[key]) process.env[key] = val
  }
}

for (const rel of ['.env.local', '.env', 'client/.env.local', 'client/.env']) {
  loadEnvFile(path.join(process.cwd(), rel))
}

const url =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  process.env.VITE_SUPABASE_URL
const anonKey =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.VITE_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY

type Payload = {
  source: 'supabase' | 'snapshot-fallback'
  tours: Array<{
    id: string
    slug: string | null
    price_per_person_cents: number
    max_guests?: number | null
  }>
  vehicles: Array<{
    id: string
    slug: string | null
    name: string
    capacity_min: number
    capacity_max: number
    vehicle_price_cents: number
    is_luxury: boolean
  }>
}

async function fetchLive(): Promise<Payload | null> {
  if (!url || !anonKey) return null
  const sb = createClient(url, anonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  })
  const [toursRes, vehiclesRes] = await Promise.all([
    sb
      .from('tours')
      .select(
        'id, slug, price_per_person_cents, additional_guest_price_cents, max_guests'
      )
      .order('name'),
    sb
      .from('vehicles')
      .select(
        'id, slug, name, capacity_min, capacity_max, vehicle_price_cents, vehicle_surcharge_cents, is_luxury'
      )
      .order('name'),
  ])
  if (toursRes.error || vehiclesRes.error) {
    console.warn(
      'refresh-catalog-pricing: Supabase error —',
      toursRes.error?.message || vehiclesRes.error?.message
    )
    return null
  }
  const tours = (toursRes.data ?? [])
    .filter((t) => t.slug)
    .map((t) => ({
      id: String(t.id),
      slug: t.slug as string,
      price_per_person_cents: Number(
        t.price_per_person_cents ?? t.additional_guest_price_cents ?? 0
      ),
      max_guests: t.max_guests != null ? Number(t.max_guests) : 5,
    }))
  const vehicles = (vehiclesRes.data ?? []).map((v) => ({
    id: String(v.id),
    slug: (v.slug as string) || null,
    name: String(v.name),
    capacity_min: Number(v.capacity_min),
    capacity_max: Number(v.capacity_max),
    vehicle_price_cents: Number(
      v.vehicle_price_cents ?? v.vehicle_surcharge_cents ?? 0
    ),
    is_luxury: Boolean(v.is_luxury),
  }))
  if (!tours.length || !vehicles.length) return null
  return { source: 'supabase', tours, vehicles }
}

function sortVehicles(vehicles: Payload['vehicles']) {
  const order = ['corolla', 'suzuki', 'mercedes']
  return [...vehicles].sort((a, b) => {
    const ai = order.indexOf(a.slug || '')
    const bi = order.indexOf(b.slug || '')
    const ar = ai === -1 ? 99 : ai
    const br = bi === -1 ? 99 : bi
    if (ar !== br) return ar - br
    return a.name.localeCompare(b.name)
  })
}

function writeGenerated(payload: Payload) {
  const body = {
    source: payload.source,
    tours: payload.tours,
    vehicles: sortVehicles(payload.vehicles),
  }
  const contents = `/** Generated by scripts/refresh-catalog-pricing.ts — do not edit by hand. */
export const BUILD_CATALOG_PRICING = ${JSON.stringify(body, null, 2)} as const
`
  fs.writeFileSync(OUT, contents, 'utf8')
}

async function main() {
  let payload: Payload | null = null
  try {
    payload = await fetchLive()
  } catch (e) {
    console.warn('refresh-catalog-pricing: fetch failed —', e)
  }
  if (!payload) {
    console.warn(
      'refresh-catalog-pricing: using CATALOG_PRICING_SNAPSHOT_FALLBACK (check Supabase env for live admin prices on next deploy).'
    )
    payload = {
      source: 'snapshot-fallback',
      tours: [...CATALOG_PRICING_SNAPSHOT_FALLBACK.tours],
      vehicles: [...CATALOG_PRICING_SNAPSHOT_FALLBACK.vehicles],
    }
  } else {
    console.log(`refresh-catalog-pricing: loaded ${payload.tours.length} tours, ${payload.vehicles.length} vehicles from Supabase.`)
  }
  writeGenerated(payload)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
